image: gitlab.app.n-hop.com:5005/infra/ci-images/docker-cli:latest

workflow:
  auto_cancel:
    on_job_failure: all
  name: "$PIPELINE_NAME"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_NAME: "Merge request pipeline"
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      variables:
        PIPELINE_NAME: "Other scheduled pipeline"
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      variables:
        PIPELINE_NAME: "Default branch pipeline"
    - if: $CI_COMMIT_TAG =~ /^v/
      variables:
        PIPELINE_NAME: "Release pipeline"

# define stages
stages:
  - style_check
  - build

.prepare_pylint_template: &prepare_pylint_definition
  - . /etc/profile
  - pip install --upgrade pip
  - pip install pylint==3.1.0

pylint:
  stage: style_check
  allow_failure: false
  interruptible: true
  tags:
    - performance
  before_script:
    - *prepare_pylint_definition
  script:
    - |
      pylint $(git ls-files '*.py') --rcfile=${CI_PROJECT_DIR}/.pylintrc --ignore-patterns=".*_unittest.py" --disable=unused-argument

build-generic-container:
  stage: build
  interruptible: true
  allow_failure: false
  tags:
    - docker
  rules:
    - changes:
        - "Dockerfile.ubuntu-generic"
  variables:
    IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH/ubuntu-generic
    DOCKERFILE: Dockerfile.ubuntu-generic
  script:
    - >
      docker build
      --pull
      --push
      --provenance false
      --tag $IMAGE_NAME:dev
      --tag $IMAGE_NAME:latest
      --tag $IMAGE_NAME:$CI_COMMIT_SHA
      --file $DOCKERFILE .

build-modified-containernet:
  stage: build
  interruptible: true
  allow_failure: false
  tags:
    - docker
  rules:
    - changes:
        - "Dockerfile.containernet"
  variables:
    IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH/containernet
    DOCKERFILE: Dockerfile.containernet
  script:
    - >
      docker build
      --pull
      --push
      --provenance false
      --tag $IMAGE_NAME:dev
      --tag $IMAGE_NAME:latest
      --tag $IMAGE_NAME:$CI_COMMIT_SHA
      --file $DOCKERFILE .
