# test case yaml file is only visible to the `run_test.py`
containernet:
  node_config:
    config_name: default
    config_file: predefined.node_config.yaml

tests:
  test1000:
    description: "Test BATS protocol with different RTT and loss rate"
    topology:
      config_name: linear_network_rtt_loss
      config_file: predefined.topology.yaml
    target_protocols: [brtp_proxy]
    route: static_route
    test_tools:
      iperf:
        interval: 1
        interval_num: 10
        packet_type: tcp
        client_host: 0
        server_host: 1
    execution_mode: parallel # parallel or serial
