containernet:
  default: # n-hop default containernet configuration
    image: gitlab.app.n-hop.com:5005/dependencies/oasis/containernet:latest
    privileged: true
    network_mode: "host"
    mounts:
      - "/var/run/docker.sock:/var/run/docker.sock"
  n-hop-local-dev: # n-hop dev containernet configuration for local development
    image: gitlab.app.n-hop.com:5005/dependencies/oasis/containernet:latest
    privileged: true
    containernet_repo_from_user: true # If true, will mount `containernet_repo_path`.
    containernet_repo_path: "/home/{user_name}/workspace/containernet"
    network_mode: "host"
    mounts:
      - "/var/run/docker.sock:/var/run/docker.sock"
  official:
    image: containernet:latest
    privileged: true
    network_mode: "host"
    mounts:
      - "/var/run/docker.sock:/var/run/docker.sock"
