containernet:
  nuc_sz:
    image: gitlab.app.n-hop.com:5005/n-hop/bats-protocol-framework/bats_containernet:dev
    privileged: true
    network_mode: "host"
    mounts:
      - "/var/run/docker.sock:/var/run/docker.sock"
  default:
    image: containernet:latest
    privileged: true
    network_mode: "host"
    mounts:
      - "/var/run/docker.sock:/var/run/docker.sock"
