# test case yaml file is only visible to the `run_test.py`
test:
  TEST_CASE_1:
    description: "Test example"
    if: true # set false, if you want to skip this test
    topology:
      config_name: linear_network_6
      config_file: src/config/predefined.topology.yaml
    node_config:
      config_name: default
      config_file: src/config/predefined.node_config.yaml
    strategy:
      matrix:
        target_protocols: [btp, brtp, brtp_proxy] # brtp, brtp_proxy, kcp, tcp
        bats_protocol_version: [latest] # v3.5.0, latest
    route: static_route
    test_tools:
      - name: iperf
        interval: 1
        interval_num: 20
        client_host: 0
        server_host: 5
