topology: # loading from file
  config_name: linear_network_6 #4-hops-linear-network
  config_file: src/config/predefined.topology.yaml
node_config:
  node_img: ubuntu:22.04
  node_vols:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/lib/modules/:/lib/modules/:ro"
    - "/usr/lib/linux-tools/:/usr/lib/linux-tools/:ro"
  node_bind_port: True
  node_name_prefix: h
  node_route: ip # or olsr
  node_ip_range: 10.10.0.0/16
