protocols:
  - name: tcp-cubic
    version: cubic
    type: distributed
  - name: tcp-reno
    version: reno
    type: distributed
  - name: tcp-bbr
    version: bbr
    type: distributed
  - name: btp
    type: distributed
    path: bats/bats_protocol
    args:
      - "--daemon_enabled=true"
      - "--tun_protocol=BTP"
    version: latest
  - name: brtp
    type: distributed
    path: bats/bats_protocol
    args:
      - "--daemon_enabled=true"
      - "--tun_protocol=BRTP"
    version: latest
  - name: brtp_proxy
    type: distributed
    path: bats/bats_protocol
    args:
      - "--daemon_enabled=true"
    version: latest
  - name: kcp
    type: none_distributed
    args: # global args for kcp
      - "-mode fast3"
      - "--datashard 10 --parityshard 3 -nocomp"
      - "-sockbuf 16777217 -dscp 46 --crypt=none"
    port: 10100 # add it to bats proxy exclude list
    protocols: # iterative
      - name: kcp_client
        path: bin/kcp/client_linux_amd64
        args:
          - "-r %s:4000 -l :%s" # %s is the ip address of the server, %s is the protocol forward
      - name: kcp_server
        path: bin/kcp/server_linux_amd64
        args:
          - "-l :4000 -t %s:%s"
