# **init_value**: initial value, must be set. if all same, give one value; other wise, give the whole value list.
# **json_description**: path to json file which contains the description of the topology in details.
# **array_description**: the array_description of the topology, only available for the linear topology.
topology:
  - name: linear_network_6
    topology_type: linear
    nodes: 7
    array_description:
      - link_loss:
        init_value: [5]
      - link_latency:
        init_value: [1]
      - link_jitter:
        init_value: [0]
      - link_bandwidth_forward:
        init_value: [100]
      - link_bandwidth_backward:
        init_value: [100]
  - name: linear_network_1
    topology_type: linear
    nodes: 2
    array_description:
      - link_loss:
        init_value: [5]
      - link_latency:
        init_value: [10]
      - link_jitter:
        init_value: [0]
      - link_bandwidth_forward:
        init_value: [100]
      - link_bandwidth_backward:
        init_value: [100]
  - name: long_fat_network
    topology_type: linear
    nodes: 2
    array_description:
      - link_loss:
        init_value: [0.01]
      - link_latency:
        init_value: [100]
      - link_jitter:
        init_value: [0]
      - link_bandwidth_forward:
        init_value: [1000]
      - link_bandwidth_backward:
        init_value: [1000]
  - name: linear_network_3
    topology_type: linear
    nodes: 4
    array_description:
      - link_loss:
        init_value: [5]
      - link_latency:
        init_value: [10]
      - link_jitter:
        init_value: [0]
      - link_bandwidth_forward:
        init_value: [100]
      - link_bandwidth_backward:
        init_value: [100]
  - name: linear_network_2
    topology_type: linear
    nodes: 3
    array_description:
      - link_loss:
        init_value: [2]
      - link_latency:
        init_value: [10]
      - link_jitter:
        init_value: [0]
      - link_bandwidth_forward:
        init_value: [100]
      - link_bandwidth_backward:
        init_value: [100]
  - name: 4-hops-linear-network
    topology_type: linear
    nodes: 5
    json_description: 4-hops-linear-network.json
  - name: linear_network_1_20
    topology_type: linear
    nodes: 2
    array_description:
      - link_loss:
        init_value: [20]
      - link_latency:
        init_value: [10]
      - link_jitter:
        init_value: [0]
      - link_bandwidth_forward:
        init_value: [100]
      - link_bandwidth_backward:
        init_value: [100]
  - name: linear_network_rtt_loss
    topology_type: linear
    nodes: 2
    array_description:
      - link_loss:
        init_value: [0]
        step_len: 2
        step_num: 5
      - link_latency:
        init_value: [10]
        step_len: 20
        step_num: 5
      - link_jitter:
        init_value: [0]
      - link_bandwidth_forward:
        init_value: [100]
      - link_bandwidth_backward:
        init_value: [100]
  - name: complex_mesh_net_l3
    topology_type: mesh
    nodes: 8
    json_description: mesh-network.json
  - name: complex_mesh_net
    topology_type: mesh
    nodes: 8
    json_description: mesh-network-no-loss.json
