# test case yaml file is only visible to the `run_test.py`
containernet:
  node_config:
    config_name: default
    config_file: src/config/predefined.node_config.yaml

tests:
  test_example:
    description: "Test example"
    topology:
      config_name: linear_network_1
      config_file: src/config/predefined.topology.yaml
    strategy:
      matrix:
        target_protocols: [brtp, kcp] # brtp, brtp_proxy, kcp, tcp
        bats_version: [latest] # v3.5.0, latest
        tcp_version: [cubic] # default:cubic; optional: bbr, reno
        kcp_version: [latest]
    route: static_route
    test_tools:
      - name: iperf
        interval: 1
        interval_num: 10
        client_host: 0
        server_host: 1
  bats_throughput_test:
    description: "Test example"
    if: false
    topology:
      config_name: linear_network_6
      config_file: src/config/predefined.topology.yaml
    strategy:
      matrix:
        target_protocols: [btp, brtp, brtp_proxy]
        bats_version: [v3.5.4]
    route: static_route
    test_tools:
      - name: iperf
        interval: 1
        interval_num: 10
        client_host: 0
        server_host: 6
