# test case yaml file is only visible to the `run_test.py`
containernet:
  node_config:
    config_name: default
    config_file: src/config/predefined.node_config.yaml

tests:
  test2:
    description: "Test protocol throughput/rtt on multiple hops"
    topology:
      config_name: linear_network_3
      config_file: src/config/predefined.topology.yaml
    target_protocols: [btp, brtp, brtp_proxy, kcp, tcp-bbr]
    route: static_route
    test_tools:
      iperf:
        interval: 1
        interval_num: 40
        client_host: 0
        server_host: 3
      rtt:
        interval: 0.01
        packet_count: 2000
        packet_size: 1014
        client_host: 0
        server_host: 3
