# test case yaml file is only visible to the `run_test.py`
containernet:
  node_config:
    config_name: default
    config_file: src/config/predefined.node_config.yaml

tests:
  test1:
    description: "Test protocol throughput/rtt on single hop"
    topology:
      config_name: linear_network_1
      config_file: src/config/predefined.topology.yaml
    target_protocols:
      - name: kcp
        type: none_distributed
        args:
          - "-mode fast3"
          - "--datashard 10 --parityshard 3 -nocomp"
          - "-sockbuf 16777217 -dscp 46 --crypt=none"
        port: 5201
        protocols: # iterative
          - name: kcp_client
            path: bin/kcp/client_linux_amd64
            args:
              - "-r %s:4000 -l :%s" # %s is the ip address of the server, %s is the protocol forward port.
          - name: kcp_server
            path: bin/kcp/server_linux_amd64
            args:
              - "-l :4000"
      - name: btp
        type: distributed
        path: bats/bats_protocol
        args:
          - "--daemon_enabled=true"
          - "--tun_protocol=BTP"
        version: latest
      - name: brtp
        type: distributed
        path: bats/bats_protocol
        args:
          - "--daemon_enabled=true"
          - "--tun_protocol=BRTP"
    route: static_route
    test_tools:
      iperf:
        interval: 1
        interval_num: 30
        client_host: 0
        server_host: 1
      rtt:
        interval: 0.01
        packet_count: 1000
        packet_size: 1014
        client_host: 0
        server_host: 1
