# test case yaml file is only visible to the `run_test.py`
containernet:
  node_config:
    config_name: default
    config_file: predefined.node_config.yaml

tests:
  test2:
    description: "Test protocol throughput/rtt on multiple hops"
    topology:
      config_name: linear_network_2
      config_file: predefined.topology.yaml
    target_protocols: [brtp_proxy] # btp, brtp, kcp, tcp-bbr
    route: static_route
    test_tools:
      iperf:
        interval: 1
        interval_num: 10
        client_host: 0
        server_host: 2
