# test case yaml file is only visible to the `run_test.py`
containernet:
  node_config:
    config_name: default
    config_file: predefined.node_config.yaml

tests:
  test10:
    description: "Test scp with multiple files"
    topology:
      config_name: linear_network_1
      config_file: predefined.topology.yaml
    target_protocols: [tcp-bbr]
    route: static_route
    test_tools:
      scp:
        client_host: 0
        server_host: 1
