# test case yaml file is only visible to the `run_test.py`
containernet:
  node_config:
    config_name: default
    config_file: predefined.node_config.yaml

tests:
  test1:
    description: "Flow competition test with multiple protocols"
    topology:
      config_name: complex_mesh_net
      config_file: predefined.topology.yaml
    target_protocols: [tcp-bbr]
    route: static_bfs
    test_tools:
      iperf:
        interval: 1
        interval_num: 10
        packet_type: tcp
        client_host: 1
        server_host: 6
    flow_generator:
        - flow_type: tcp
          client_host: 0
          server_host: 5
        - flow_type: tcp
          client_host: 1
          server_host: 6