containernet:
  nuc_sz:
    image: bats_containernet:dev
    privileged: true
    network_mode: "host"
    mounts:
      - "/var/run/docker.sock:/var/run/docker.sock"
  nix_hk:
    image: gitlab.app.n-hop.com:5005/n-hop/bats-protocol-framework/bats_containernet:dev
    privileged: true
    network_mode: "host"
    dns_server:
      - "172.16.250.9"
    dns_resolve:
      - "gitlab.app.n-hop.com:172.16.250.10"
    mounts:
      - "/var/run/docker.sock:/var/run/docker.sock"